// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';

const SUPABASE_URL = "https://eencnctntsydevijdhdu.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImVlbmNuY3RudHN5ZGV2aWpkaGR1Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3MjkzNDk3NjQsImV4cCI6MjA0NDkyNTc2NH0.q_7cWRaCt8-u1_KavWdIggllWPieQ93mc7uukCAsGKY";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);